// English translations for inverter fault database
// Maps Portuguese source strings to English translations
window.faultsEn = {
    // Descriptions
    'Sobrecarga do motor': 'Motor overload',
    'Sobrecarga do motor IT': 'Motor I²T overload',
    'Sobrecarga do motor I²T': 'Motor I²T overload',
    'Sobrecarga do motor I2T': 'Motor I²T overload',
    'Sobrecarga do inversor': 'Inverter overload',
    'Sobrecarga motor': 'Motor overload',
    'Sobrecarga motor IT': 'Motor I²T overload',
    'Sobrecarga motor ETR': 'Motor ETR overload',
    'Sobrecarga ETR motor': 'Motor ETR overload',
    'Sobrecarga IT': 'I²T overload',
    'Sobrecarga IT do motor': 'Motor I²T overload',
    'Sobrecarga': 'Overload',
    'Sobrecarga do motor (IT)': 'Motor thermal overload',
    'Sobrecarga I2T': 'I²T overload',
    'Sobrecarga do motor IT': 'Motor I²T overload',
    'Sobrecarga térmica do motor': 'Motor thermal overload',

    'Sobretensão no barramento DC': 'DC bus overvoltage',
    'Sobretensão no barramento CC': 'DC bus overvoltage',
    'Sobretensão barramento CC': 'DC bus overvoltage',
    'Sobretensão barramento': 'DC bus overvoltage',
    'Sobretensão no barramento': 'DC bus overvoltage',
    'Sobretensão no link CC': 'DC link overvoltage',
    'Sobretensão na alimentação': 'Supply overvoltage',
    'Sobretensão': 'Overvoltage',
    'Sobretensão barramento CC': 'DC bus overvoltage',

    'Subtensão no barramento DC': 'DC bus undervoltage',
    'Subtensão no barramento CC': 'DC bus undervoltage',
    'Subtensão barramento CC': 'DC bus undervoltage',
    'Subtensão na alimentação': 'Supply undervoltage',
    'Subtensão barramento': 'DC bus undervoltage',
    'Subtensão': 'Undervoltage',

    'Curto-circuito na saída': 'Output short circuit',
    'Curto-circuito saída': 'Output short circuit',
    'Curto-circuito': 'Short circuit',
    'Curto na saída': 'Output short',
    'Curto no motor': 'Motor short circuit',

    'Falha de comunicação CAN': 'CAN communication fault',
    'Falha de comunicação serial': 'Serial communication fault',
    'Falha de comunicação': 'Communication fault',
    'Falha de comunicação PROFIBUS': 'PROFIBUS communication fault',
    'Falha de comunicação fieldbus': 'Fieldbus communication fault',
    'Falha na comunicação': 'Communication fault',
    'Falha de comunicação entre placas': 'Inter-board communication fault',
    'Falha na conexão da IHM remota': 'Remote HMI connection fault',
    'Erro de comunicação serial': 'Serial communication error',
    'Falha comunicação': 'Communication fault',
    'Falha de comunicação CANopen': 'CANopen communication fault',
    'Falha de comunicação DeviceNet': 'DeviceNet communication fault',
    'Falha de comunicação EtherNet/IP': 'EtherNet/IP communication fault',
    'Falha de comunicação EtherCAT': 'EtherCAT communication fault',
    'Falha de comunicação Modbus': 'Modbus communication fault',
    'Falha de comunicação PROFINET': 'PROFINET communication fault',
    'Falha de comunicação CC-Link': 'CC-Link communication fault',

    'Erro de parametrização': 'Parameter setting error',
    'Falha no ventilador': 'Fan fault',
    'Falha no encoder': 'Encoder fault',
    'Falha no circuito de gate-drive': 'Gate drive circuit fault',
    'Falha no circuito de pré-carga': 'Pre-charge circuit fault',
    'Falha no circuito de frenagem': 'Braking circuit fault',
    'Falha de hardware na placa de controle': 'Control board hardware fault',
    'Falha de hardware': 'Hardware fault',
    'Falha de hardwaré': 'Hardware fault',

    'Temperatura do dissipador elevada': 'Heatsink high temperature',
    'Temperatura do dissipador excessiva': 'Heatsink overtemperature',
    'Temperatura do dissipador alta': 'Heatsink high temperature',
    'Temperatura dissipador alta': 'Heatsink high temperature',
    'Temperatura dissipador excessiva': 'Heatsink overtemperature',
    'Temperatura interna elevada': 'Internal high temperature',
    'Temperatura interna alta': 'Internal high temperature',
    'Temperatura excessiva': 'Overtemperature',
    'Temperatura do motor elevada (PTC)': 'Motor high temperature (PTC)',
    'Temperatura do motor elevada': 'Motor high temperature',
    'Temperatura do inversor elevada': 'Inverter high temperature',
    'Temperatura do dissipador excessiva': 'Heatsink overtemperature',
    'Temperatura do dissipador elevada': 'Heatsink high temperature',

    'Perda de fase na entrada': 'Input phase loss',
    'Perda de fase na rede': 'Mains phase loss',
    'Perda de fase': 'Phase loss',
    'Falha PTC do motor': 'Motor PTC fault',
    'Superaquecimento': 'Overheating',
    'Falha no aterramento': 'Ground fault',
    'Falha aterramento': 'Ground fault',
    'Falha no power module': 'Power module fault',
    'Falha DRIVE-CLiQ': 'DRIVE-CLiQ fault',
    'Falha no motor (temp. sensor)': 'Motor temperature sensor fault',
    'Aviso de sobrecarga do motor IT': 'Motor I²T overload warning',
    'Falha interna': 'Internal fault',
    'Falha na placa de controle': 'Control board fault',
    'Falha na memória do cartão': 'Memory card fault',
    'Falha no ventilador do inversor': 'Inverter fan fault',
    'Falha IGBT temperatura': 'IGBT temperature fault',
    'Falha ventilador': 'Fan fault',
    'Falha ventilador inversor': 'Inverter fan fault',
    'Falha encoder': 'Encoder fault',
    'Falha no motor (sensor PTC)': 'Motor sensor (PTC) fault',
    'Falha no motor': 'Motor fault',
    'Falha na placa principal': 'Main board fault',
    'Falha na fonte interna': 'Internal power supply fault',
    'Falha no contator de freio': 'Brake contactor fault',
    'Falha no resistor de freio': 'Braking resistor fault',
    'Falha no chopper de freio': 'Brake chopper fault',
    'Falha na unidade de frenagem': 'Braking unit fault',
    'Falha no relé térmico': 'Thermal relay fault',
    'Falha no disjuntor': 'Circuit breaker fault',
    'Falha no contator principal': 'Main contactor fault',
    'Falha no fusível': 'Fuse fault',
    'Falha no sensor de temperatura': 'Temperature sensor fault',
    'Falha na ventoinha': 'Fan fault',
    'Falha no termostato': 'Thermostat fault',
    'Falha na placa de potência': 'Power board fault',
    'Falha na placa de interface': 'Interface board fault',
    'Falha na placa de comunicação': 'Communication board fault',
    'Falha na placa de controle': 'Control board fault',
    'Falha no módulo de potência': 'Power module fault',
    'Falha no módulo IGBT': 'IGBT module fault',
    'Falha no módulo de retificação': 'Rectifier module fault',
    'Falha no módulo de freio': 'Brake module fault',
    'Falha no módulo de entrada': 'Input module fault',
    'Falha no módulo de saída': 'Output module fault',

    // Symptoms
    'Motor superaquecido': 'Motor overheating',
    'Corrente acima do nominal': 'Current above rated',
    'Atuação frequente em regime': 'Frequent tripping at steady state',
    'Perda de comunicação com periféricos': 'Loss of communication with peripherals',
    'Parada súbita do inversor': 'Sudden inverter stop',
    'LED de comunicação apagado': 'Communication LED off',
    'Desarme durante desaceleração': 'Trip during deceleration',
    'Tensão do barramento CC acima do limite': 'DC bus voltage above limit',
    'Alarme de sobretensão frequente': 'Frequent overvoltage alarm',
    'Inversor não acelera': 'Inverter does not accelerate',
    'Queda de tensão momentânea': 'Momentary voltage sag',
    'Desarme em partidas': 'Trip at startup',
    'Desarme imediato ao partir': 'Immediate trip at start',
    'Fusível queimado': 'Blown fuse',
    'Cheiro de queimado no motor': 'Burning smell from motor',
    'Inversor não opera conforme esperado': 'Inverter does not operate as expected',
    'Parâmetros incorretos na tela': 'Incorrect parameters on display',
    'Falha após alteração de parâmetros': 'Fault after parameter change',
    'Ventilador do inversor não gira': 'Inverter fan not spinning',
    'Superaquecimento do inversor': 'Inverter overheating',
    'Desarme por temperatura': 'Temperature trip',
    'Oscilação de velocidade': 'Speed oscillation',
    'Erro de posicionamento': 'Positioning error',
    'Motor vibrando em baixa rotação': 'Motor vibrating at low speed',
    'Corrente de saída excessiva': 'Excessive output current',
    'Desarme em regime permanente': 'Trip at steady state',
    'Temperatura elevada no inversor': 'High inverter temperature',
    'Ventiladores girando em alta rotação': 'Fans running at high speed',
    'Superfície do inversor quente': 'Inverter surface hot',
    'Display sem informação': 'No display information',
    'Inversor não responde a comandos': 'Inverter does not respond to commands',
    'LEDs de status apagados': 'Status LEDs off',
    'Inversor não energiza': 'Inverter does not power up',
    'Relé de pré-carga não atua': 'Pre-charge relay does not activate',
    'Tensão do barramento CC não estabiliza': 'DC bus voltage does not stabilize',
    'Ondulação no barramento CC': 'DC bus ripple',
    'Inversor opera com capacidade reduzida': 'Inverter operates with reduced capacity',
    'Desarme em carga elevada': 'Trip under high load',
    'Motor excessivamente quente': 'Motor excessively hot',
    'Desarme por PTC': 'PTC trip',
    'Cheiro de queimado': 'Burning smell',
    'Inversor não parte': 'Inverter does not start',
    'Erro no IGBT': 'IGBT error',
    'Curto-circuito no braço do inversor': 'Short circuit in inverter leg',
    'IHM remota sem comunicação': 'Remote HMI no communication',
    'Display piscando': 'Display flashing',
    'Teclas da IHM sem resposta': 'HMI keys unresponsive',
    'Motor aquecendo excessivamente': 'Motor heating excessively',
    'Corrente elevada': 'High current',
    'Atuação frequente da proteção': 'Frequent protection activation',
    'Perda de comunicação': 'Communication lost',
    'Inversor parado inesperadamente': 'Inverter stopped unexpectedly',
    'Erro no barramento': 'Bus error',
    'Desarme na desaceleração': 'Trip during deceleration',
    'Tensão CC excessiva': 'Excessive DC voltage',
    'Alarme de sobretensão': 'Overvoltage alarm',
    'Perda de referência de velocidade': 'Speed reference loss',
    'Oscilação do motor': 'Motor oscillation',
    'Erro de seguimento': 'Tracking error',
    'Desarme frequente': 'Frequent tripping',
    'Inversor desarma ao partir': 'Inverter trips at start',
    'Queda de tensão na rede': 'Mains voltage sag',
    'Falha intermitente': 'Intermittent fault',
    'Ventilador parado': 'Fan stopped',
    'Ruído anormal no inversor': 'Abnormal inverter noise',
    'Display escuro intermitente': 'Display intermittent dark',
    'Desarme em carga': 'Trip under load',
    'Motor aquecendo': 'Motor heating',
    'Corrente de saída elevada': 'High output current',
    'Proteção térmica atuando': 'Thermal protection active',
    'Rede industrial offline': 'Industrial network offline',
    'Inversor não responde': 'Inverter does not respond',
    'Erro de link': 'Link error',
    'Variação de velocidade': 'Speed variation',
    'Motor não mantém rotação': 'Motor does not maintain speed',
    'Erro de posição': 'Position error',
    'Ondulação no torque': 'Torque ripple',
    'Inversor opera instável': 'Inverter operates unstable',
    'Desarme em alta carga': 'Trip at high load',
    'Corrente do motor acima do limite': 'Motor current above limit',
    'Desarme da conversora': 'Converter trip',
    'Fusível de potência queimado': 'Power fuse blown',
    'Curto no motor': 'Motor short circuit',
    'Ventiladores em máxima rotação': 'Fans at maximum speed',
    'Perda de comunicação com CLP': 'PLC communication lost',
    'Rede offline': 'Network offline',
    'Falha de telegrama': 'Telegram fault',
    'Parâmetros perdidos ao religar': 'Parameters lost on power cycle',
    'Erro de inicialização': 'Initialization error',
    'Falha ao carregar configuração': 'Failed to load configuration',
    'Alarme de corrente elevada': 'High current alarm',
    'Limite térmico próximo': 'Thermal limit near',
    'Operação em sobrecarga': 'Overload operation',
    'Desarme por sobrecarga': 'Overload trip',
    'Corrente elevada por período prolongado': 'High current for extended period',
    'Desarme em desaceleração': 'Trip during deceleration',
    'Tensão CC acima do limite': 'DC voltage above limit',
    'Falha em parada rápida': 'Fast stop fault',
    'Tensão CC muito baixa': 'DC voltage too low',
    'Desarme ao acelerar': 'Trip during acceleration',
    'Inversor sem resposta': 'Inverter unresponsive',
    'Display apagado': 'Display off',
    'Falha na placa principal': 'Main board fault',
    'Estalo audível': 'Audible pop',
    'Curto na saída': 'Output short',
    'Corrente do motor elevada': 'High motor current',
    'Motor quente': 'Hot motor',
    'IT atuou': 'I²T activated',
    'Tensão CC muito alta': 'DC voltage too high',
    'Desarme desaceleração': 'Deceleration trip',
    'Parada de emergência': 'Emergency stop',
    'Sensor KTY/PTC com defeito': 'Defective KTY/PTC sensor',
    'Fio do sensor partido': 'Sensor wire broken',
    'Motor oscila': 'Motor oscillates',
    'Falha no seguimento': 'Tracking fault',
    'Módulo de potência não responde': 'Power module unresponsive',
    'LED de erro aceso': 'Error LED on',
    'Falha na comunicação interna': 'Internal communication fault',
    'Perda de comunicação entre módulos': 'Loss of communication between modules',
    'Erro de topologia': 'Topology error',
    'Componente não reconhecido': 'Unrecognized component',
    'Tensão CC elevada': 'High DC voltage',
    'Falha na parada': 'Stop fault',
    'Tensão CC baixa': 'Low DC voltage',
    'Falha de partida': 'Start fault',
    'Inversor não funciona': 'Inverter does not work',
    'Display sem sinal': 'No signal on display',
    'Erro na placa': 'Board error',
    'Desarme imediato': 'Immediate trip',
    'Curto na saída': 'Output short',
    'Corrente excessiva': 'Excessive current',
    'Inversor superaquecendo': 'Inverter overheating',
    'Ventilador em alta': 'Fan at high speed',
    'Alarme': 'Alarm',
    'Tensão baixa': 'Low voltage',
    'Inversor não troca dados': 'Inverter does not exchange data',
    'Parada por segurança': 'Safety stop',
    'Estouro de IGBT': 'IGBT blowout',
    'Alarme de temperatura': 'Temperature alarm',
    'Motor sobrecarregado': 'Overloaded motor',
    'Corrente nominal excedida': 'Rated current exceeded',
    'Tensão CC alta': 'High DC voltage',
    'Alarme intermitente': 'Intermittent alarm',
    'IHM remota sem resposta': 'Remote HMI unresponsive',
    'Sem comunicação RS485': 'No RS485 communication',
    'Falha de link': 'Link fault',
    'Desarme na frenagem': 'Trip during braking',
    'Tensão acima do limite': 'Voltage above limit',
    'Parada brusca': 'Abrupt stop',
    'Falha de comunicação': 'Communication fault',
    'Falha interna': 'Internal fault',
    'Display não acende': 'Display does not light up',
    'Sem comunicação com inversor': 'No communication with inverter',
    'Erro de comunicação interna': 'Internal communication error',
    'Falha ao inicializar': 'Failed to initialize',
    'Inversor inoperante': 'Inverter inoperative',
    'Erro de configuração': 'Configuration error',
    'Parâmetros inválidos': 'Invalid parameters',
    'Perda dos parâmetros': 'Parameter loss',
    'Erro de calibração': 'Calibration error',
    'Sobrecorrente na aceleração': 'Overcurrent during acceleration',
    'Sobrecorrente na desaceleração': 'Overcurrent during deceleration',
    'Sobrecorrente em regime': 'Overcurrent at steady state',
    'Corrente de pico elevada': 'High peak current',
    'Corrente RMS elevada': 'High RMS current',
    'Corrente de fuga elevada': 'High leakage current',
    'Fuga à terra': 'Ground leakage',
    'Temperatura do motor elevada': 'High motor temperature',
    'Sobrecarga térmica do motor': 'Motor thermal overload',
    'Temperatura do dissipador elevada': 'High heatsink temperature',
    'Temperatura ambiente elevada': 'High ambient temperature',
    'Temperatura do painel elevada': 'High panel temperature',
    'Ventilador com ruído': 'Noisy fan',
    'Ventilador vibrando': 'Fan vibrating',
    'Ventilador com baixa rotação': 'Fan running at low speed',
    'Ventilador com alta rotação': 'Fan running at high speed',
    'Ventilador não desliga': 'Fan does not turn off',
    'Ventilador não liga': 'Fan does not turn on',
    'Erro de comunicação serial': 'Serial communication error',
    'Erro de comunicação fieldbus': 'Fieldbus communication error',
    'Erro de comunicação rede': 'Network communication error',
    'Rede com ruído': 'Noisy network',
    'Telegrama inválido': 'Invalid telegram',
    'Timeout de comunicação': 'Communication timeout',
    'Endereço duplicado na rede': 'Duplicate network address',
    'Erro de CRC': 'CRC error',
    'Erro de paridade': 'Parity error',
    'Erro de framing': 'Framing error',
    'Erro de configuração de rede': 'Network configuration error',
    'Rede não configurada': 'Network not configured',
    'Erro de parametrização': 'Parameterization error',
    'Erro de calibração': 'Calibration error',
    'Erro de offset': 'Offset error',
    'Erro de ganho': 'Gain error',
    'Erro de linearização': 'Linearization error',
    'Sensor sem sinal': 'No sensor signal',
    'Sinal do sensor fora da faixa': 'Sensor signal out of range',
    'Curto no sensor': 'Sensor short circuit',
    'Sensor aberto': 'Open sensor',
    'Sensor com defeito': 'Defective sensor',

    // Causes  
    'Carga excessiva no motor': 'Excessive motor load',
    'Tempo de aceleração muito curto': 'Acceleration time too short',
    'Ventilação do motor obstruída': 'Motor ventilation obstructed',
    'Cabo CAN danificado ou mal conectado': 'CAN cable damaged or poorly connected',
    'Terminação de rede incorreta': 'Incorrect network termination',
    'Fonte de alimentação dos periféricos insuficiente': 'Insufficient peripheral power supply',
    'Rampa de desaceleração muito curta': 'Deceleration ramp too short',
    'Tensão de rede elevada': 'High mains voltage',
    'Freio regenerativo inadequado': 'Inadequate regenerative brake',
    'Tensão de rede abaixo do mínimo': 'Mains voltage below minimum',
    'Afundamento de tensão na rede': 'Mains voltage sag',
    'Contato(s) do contator principal com mau contato': 'Main contactor poor contact',
    'Curto-circuito entre fases do motor': 'Short circuit between motor phases',
    'Aterramento do motor': 'Motor grounding',
    'Isolação do motor danificada': 'Damaged motor insulation',
    'Cabos de motor danificados': 'Damaged motor cables',
    'Parâmetros incompatíveis configurados': 'Incompatible parameters configured',
    'Falha na gravação da memória': 'Memory write failure',
    'Substituição da placa de controle': 'Control board replacement',
    'Ventilador com fim de vida útil': 'Fan end of life',
    'Sujeira acumulada no ventilador': 'Dirt accumulated on fan',
    'Obstrução do fluxo de ar': 'Airflow obstruction',
    'Conexão do encoder interrompida': 'Encoder connection interrupted',
    'Encoder danificado': 'Damaged encoder',
    'Ruído elétrico no cabo do encoder': 'Electrical noise on encoder cable',
    'Corrente de carga acima da nominal do inversor': 'Load current above inverter rating',
    'Ciclo de trabalho excessivo': 'Excessive duty cycle',
    'Temperatura ambiente elevada': 'High ambient temperature',
    'Temperatura ambiente acima do limite': 'Ambient temperature above limit',
    'Ventilador defeituoso': 'Defective fan',
    'Dissipador obstruído por sujeira': 'Heatsink obstructed by dirt',
    'Placa de controle danificada': 'Damaged control board',
    'Sobretensão na placa': 'Overvoltage on board',
    'Umidade na placa eletrônica': 'Moisture on electronic board',
    'Resistor de pré-carga danificado': 'Damaged pre-charge resistor',
    'Relé de pré-carga com defeito': 'Defective pre-charge relay',
    'Circuito de disparo do tiristor aberto': 'Open thyristor firing circuit',
    'Fusível de entrada queimado': 'Blown input fuse',
    'Contator com mau contato': 'Contactor poor contact',
    'Uma fase da rede de alimentação aberta': 'One supply phase open',
    'Sobrecarga prolongada do motor': 'Prolonged motor overload',
    'Ventilação do motor insuficiente': 'Insufficient motor ventilation',
    'Placa gate-drive danificada': 'Damaged gate-drive board',
    'IGBT em curto': 'Shorted IGBT',
    'Fonte de alimentação gate-drive instável': 'Unstable gate-drive power supply',
    'Cabo de conexão danificado': 'Damaged connection cable',
    'Conector RJ45 mal encaixado': 'RJ45 connector loosely seated',
    'IHM com defeito': 'Defective HMI',
    'Carga mecânica excessiva': 'Excessive mechanical load',
    'Aceleração muito rápida': 'Acceleration too fast',
    'Ventilação do motor prejudicada': 'Impaired motor ventilation',
    'Fiação de rede solta': 'Loose network wiring',
    'Configuração de baudrate incorreta': 'Incorrect baud rate setting',
    'Terminação de rede ausente': 'Missing network termination',
    'Regeneração excessiva': 'Excessive regeneration',
    'Tensão de rede muito alta': 'Mains voltage too high',
    'Cabo do encoder rompido': 'Broken encoder cable',
    'Ruído elétrico': 'Electrical noise',
    'Corrente acima da nominal': 'Current above rated',
    'Ventilação insuficiente': 'Insufficient ventilation',
    'Tensão de alimentação instável': 'Unstable supply voltage',
    'Fim de vida útil do ventilador': 'Fan end of life',
    'Sujeira acumulada': 'Accumulated dirt',
    'Obstrução mecânica': 'Mechanical obstruction',
    'Tensão de rede baixa': 'Low mains voltage',
    'Pré-carga incompleta': 'Incomplete pre-charge',
    'Falha no retificador': 'Rectifier failure',
    'Carga excessiva': 'Excessive load',
    'Tempo de aceleração curto': 'Short acceleration time',
    'Motor subdimensionado': 'Undersized motor',
    'Rampa de desaceleração muito rápida': 'Deceleration ramp too fast',
    'Frenagem regenerativa excessiva': 'Excessive regenerative braking',
    'Cabo serial danificado': 'Damaged serial cable',
    'Configuração de rede incorreta': 'Incorrect network configuration',
    'Placa de comunicação com defeito': 'Defective communication board',
    'Cabos de motor danificados': 'Damaged motor cables',
    'PTC mal ajustado': 'Poorly adjusted PTC',
    'Carga acima do especificado': 'Load above specification',
    'Rampa aceleração muito curta': 'Acceleration ramp too short',
    'Desaceleração muito rápida': 'Deceleration too fast',
    'Carga regenerativa': 'Regenerative load',
    'Cabo danificado': 'Damaged cable',
    'Configuração incorreta': 'Incorrect configuration',
    'Rampa de aceleração insuficiente': 'Insufficient acceleration ramp',
    'Fator de serviço excedido': 'Service factor exceeded',
    'Energia regenerativa excessiva': 'Excessive regenerative energy',
    'Desaceleração abrupta': 'Abrupt deceleration',
    'Rede de alimentação instável': 'Unstable supply network',
    'Cabo de rede danificado': 'Damaged network cable',
    'Terminação ausente': 'Missing termination',
    'Endereço duplicado': 'Duplicate address',
    'Encoder com defeito': 'Defective encoder',
    'Interferência eletromagnética': 'Electromagnetic interference',
    'Fase da rede ausente': 'Missing mains phase',
    'Ventilador danificado': 'Damaged fan',
    'Acúmulo de poeira': 'Dust accumulation',
    'Carga excessiva no motor': 'Excessive motor load',
    'Tempo de aceleração muito curto': 'Acceleration time too short',
    'Motor subdimensionado': 'Undersized motor',
    'Fusível de entrada queimado': 'Blown input fuse',
    'Tensão de rede abaixo do mínimo': 'Mains voltage below minimum',
    'Uma fase da rede de alimentação aberta': 'One supply phase open',
    'Falha no contator principal': 'Main contactor fault',
    'Falha no disjuntor principal': 'Main circuit breaker fault',
    'Falha no fusível de entrada': 'Input fuse fault',
    'Falha no transformador': 'Transformer fault',
    'Falha no retificador': 'Rectifier fault',
    'Falha no capacitor do barramento': 'Bus capacitor fault',
    'Falha no indutor': 'Inductor fault',
    'Falha no resistor de pré-carga': 'Pre-charge resistor fault',
    'Falha no relé de pré-carga': 'Pre-charge relay fault',
    'Falha no contator de pré-carga': 'Pre-charge contactor fault',
    'Falha no tiristor de pré-carga': 'Pre-charge thyristor fault',
    'Falha no IGBT': 'IGBT fault',
    'Falha no diodo': 'Diode fault',
    'Falha no módulo IGBT': 'IGBT module fault',
    'Falha no módulo de potência': 'Power module fault',
    'Falha no driver IGBT': 'IGBT driver fault',
    'Falha na fonte gate-drive': 'Gate-drive power supply fault',
    'Falha no circuito de disparo': 'Firing circuit fault',
    'Falha no circuito de proteção': 'Protection circuit fault',
    'Falha no circuito de medição': 'Measurement circuit fault',
    'Falha no sensor de corrente': 'Current sensor fault',
    'Falha no sensor de tensão': 'Voltage sensor fault',
    'Falha no sensor de temperatura': 'Temperature sensor fault',
    'Falha no encoder': 'Encoder fault',
    'Falha no resolver': 'Resolver fault',
    'Falha no tacogerador': 'Tachogenerator fault',
    'Falha na IHM': 'HMI fault',
    'Falha na placa de controle': 'Control board fault',
    'Falha na placa de potência': 'Power board fault',
    'Falha na placa de comunicação': 'Communication board fault',
    'Falha na placa de interface': 'Interface board fault',
    'Falha na placa de relés': 'Relay board fault',
    'Falha na placa de entradas/saídas': 'I/O board fault',
    'Falha na placa de frenagem': 'Braking board fault',
    'Falha na fonte auxiliar': 'Auxiliary power supply fault',
    'Falha na fonte interna': 'Internal power supply fault',
    'Falha na fonte externa': 'External power supply fault',
    'Falha no ventilador': 'Fan fault',
    'Falha no termostato': 'Thermostat fault',
    'Falha no contator de freio': 'Brake contactor fault',
    'Falha no resistor de freio': 'Braking resistor fault',
    'Falha no chopper de freio': 'Brake chopper fault',

    // Solutions
    'Reduzir a carga do motor': 'Reduce motor load',
    'Aumentar o tempo de aceleração (P0100)': 'Increase acceleration time (P0100)',
    'Melhorar a ventilação do motor': 'Improve motor ventilation',
    'Verificar conexão do cabo CAN': 'Check CAN cable connection',
    'Ajustar resistores de terminação (120 ohms)': 'Adjust termination resistors (120 ohms)',
    'Verificar fonte de alimentação': 'Check power supply',
    'Aumentar tempo de desaceleração (P0102)': 'Increase deceleration time (P0102)',
    'Instalar resistor de freio': 'Install braking resistor',
    'Utilizar módulo de frenagem regenerativa': 'Use regenerative braking module',
    'Verificar tensão de alimentação': 'Check supply voltage',
    'Instalar contator de força adequado': 'Install suitable power contactor',
    'Verificar conexões e contatos do contator': 'Check contactor connections and contacts',
    'Verificar isolação do motor com megôhmetro': 'Check motor insulation with megger',
    'Inspecionar cabos do motor': 'Inspect motor cables',
    'Substituir motor se necessário': 'Replace motor if necessary',
    'Verificar conexões nos bornes': 'Check terminal connections',
    'Restaurar parâmetros de fábrica (P0204)': 'Restore factory parameters (P0204)',
    'Realizar nova parametrização': 'Perform new parameterization',
    'Atualizar firmware do inversor': 'Update inverter firmware',
    'Substituir o ventilador danificado': 'Replace damaged fan',
    'Limpar o ventilador e dissipadores': 'Clean fan and heatsinks',
    'Verificar funcionamento do termostato': 'Check thermostat operation',
    'Verificar conexão do encoder': 'Check encoder connection',
    'Substituir encoder': 'Replace encoder',
    'Utilizar cabo blindado para encoder': 'Use shielded cable for encoder',
    'Redimensionar inversor para corrente maior': 'Resize inverter for higher current',
    'Reduzir frequência de operação': 'Reduce operating frequency',
    'Melhorar ventilação do painel': 'Improve panel ventilation',
    'Reduzir temperatura do painel': 'Reduce panel temperature',
    'Limpar dissipador de calor': 'Clean heatsink',
    'Verificar funcionamento dos ventiladores': 'Check fan operation',
    'Substituir placa de controle': 'Replace control board',
    'Verificar condições ambientais': 'Check environmental conditions',
    'Realizar reparo em assistência técnica autorizada': 'Repair at authorized service center',
    'Substituir resistor de pré-carga': 'Replace pre-charge resistor',
    'Verificar relé de pré-carga': 'Check pre-charge relay',
    'Inspecionar placa de potência': 'Inspect power board',
    'Verificar fusíveis de entrada': 'Check input fuses',
    'Inspecionar contator principal': 'Inspect main contactor',
    'Verificar tensão de alimentação trifásica': 'Check three-phase supply voltage',
    'Instalar ventoinha de refrigeração auxiliar': 'Install auxiliary cooling fan',
    'Reduzir ciclo de trabalho': 'Reduce duty cycle',
    'Verificar dimensionamento do motor': 'Check motor sizing',
    'Substituir placa gate-drive': 'Replace gate-drive board',
    'Substituir módulo IGBT': 'Replace IGBT module',
    'Verificar fonte auxiliar': 'Check auxiliary power supply',
    'Verificar cabo de conexão': 'Check connection cable',
    'Reconectar IHM remota': 'Reconnect remote HMI',
    'Substituir IHM': 'Replace HMI',
    'Ajustar tempo de rampa de aceleração': 'Adjust acceleration ramp time',
    'Reduzir carga do motor': 'Reduce motor load',
    'Melhorar refrigeração do motor': 'Improve motor cooling',
    'Verificar conexões do barramento': 'Check bus connections',
    'Ajustar taxa de comunicação': 'Adjust communication rate',
    'Instalar terminação adequada': 'Install proper termination',
    'Aumentar tempo de desaceleração': 'Increase deceleration time',
    'Instalar resistor de frenagem': 'Install braking resistor',
    'Utilizar módulo regenerativo': 'Use regenerative module',
    'Verificar cabo do encoder': 'Check encoder cable',
    'Blindar cabo do encoder': 'Shield encoder cable',
    'Redimensionar o inversor': 'Resize inverter',
    'Reduzir frequência de chaveamento': 'Reduce switching frequency',
    'Verificar alimentação elétrica': 'Check electrical supply',
    'Substituir contator': 'Replace contactor',
    'Verificar fusíveis': 'Check fuses',
    'Substituir ventilador': 'Replace fan',
    'Limpar o inversor': 'Clean inverter',
    'Verificar obstruções': 'Check for obstructions',
    'Inspecionar circuito de pré-carga': 'Inspect pre-charge circuit',
    'Verificar ponte retificadora': 'Check rectifier bridge',
    'Aumentar tempo de rampa': 'Increase ramp time',
    'Reduzir carga': 'Reduce load',
    'Redimensionar motor': 'Resize motor',
    'Instalar resistor de freio': 'Install braking resistor',
    'Verificar tensão de rede': 'Check mains voltage',
    'Substituir cabo serial': 'Replace serial cable',
    'Verificar configuração de rede': 'Check network configuration',
    'Substituir placa opcional': 'Replace optional board',
    'Testar isolação do motor': 'Test motor insulation',
    'Verificar cabos de saída': 'Check output cables',
    'Reduzir carga do motor': 'Reduce motor load',
    'Limpar ventilação do motor': 'Clean motor ventilation',
    'Ajustar parâmetro PTC': 'Adjust PTC parameter',
    'Reduzir carga aplicada': 'Reduce applied load',
    'Aumentar tempo de aceleração': 'Increase acceleration time',
    'Instalar ventilação auxiliar': 'Install auxiliary ventilation',
    'Substituir cabo de comunicação': 'Replace communication cable',
    'Verificar parâmetros de rede': 'Check network parameters',
    'Reparar placa de comunicação': 'Repair communication board',
    'Aumentar rampa de aceleração': 'Increase acceleration ramp',
    'Reduzir carga acoplada': 'Reduce coupled load',
    'Verificar fator de serviço do motor': 'Check motor service factor',
    'Aumentar rampa de desaceleração': 'Increase deceleration ramp',
    'Adicionar resistor de freio': 'Add braking resistor',
    'Verificar alimentação': 'Check power supply',
    'Verificar cabos e conectores': 'Check cables and connectors',
    'Configurar terminação de barramento': 'Configure bus termination',
    'Verificar endereçamento da rede': 'Check network addressing',
    'Substituir cabo do encoder': 'Replace encoder cable',
    'Trocar encoder': 'Replace encoder',
    'Utilizar cabo blindado': 'Use shielded cable',
    'Verificar alimentação trifásica': 'Check three-phase supply',
    'Limpar dissipadores': 'Clean heatsinks',
    'Aumentar rampa de aceleração': 'Increase acceleration ramp',
    'Aumentar tempo de rampa de aceleração': 'Increase acceleration ramp time',
    'Aumentar tempo de desaceleração': 'Increase deceleration time',
    'Instalar resistor de freio': 'Install braking resistor',
    'Ir para assistência técnica': 'Contact technical support',
    'Solicitar assistência técnica': 'Request technical support',
    'Substituir o inversor': 'Replace inverter',
    'Substituir peça danificada': 'Replace damaged part',
    'Verificar manual do inversor': 'Check inverter manual',
    'Contatar fabricante': 'Contact manufacturer',
    'Aumentar rampa de desaceleração': 'Increase deceleration ramp',
    'Reduzir frequência de chaveamento': 'Reduce switching frequency',
    'Reduzir temperatura do ambiente': 'Reduce ambient temperature',
    'Melhorar ventilação do painel': 'Improve panel ventilation',
    'Instalar filtro de linha': 'Install line filter',
    'Instalar reator de linha': 'Install line reactor',
    'Instalar filtro EMI': 'Install EMI filter',
    'Verificar aterramento': 'Check grounding',
    'Melhorar aterramento': 'Improve grounding',
    'Verificar blindagem dos cabos': 'Check cable shielding',
    'Instalar ferrite de supressão': 'Install suppression ferrite',
    'Separar cabos de potência e controle': 'Separate power and control cables',
    'Utilizar cabos blindados': 'Use shielded cables',
    'Substituir módulo de potência': 'Replace power module',
    'Verificar placa de potência': 'Check power board',
    'Verificar placa de controle': 'Check control board',
    'Substituir placa de potência': 'Replace power board',
    'Substituir placa de interface': 'Replace interface board',
    'Substituir placa de comunicação': 'Replace communication board',
    'Substituir módulo IGBT': 'Replace IGBT module',
    'Substituir retificador': 'Replace rectifier',
    'Substituir capacitor do barramento': 'Replace bus capacitor',
    'Substituir resistor de freio': 'Replace braking resistor',
    'Substituir chopper de freio': 'Replace brake chopper',
    'Substituir contator de freio': 'Replace brake contactor',
    'Limpar dissipador do inversor': 'Clean inverter heatsink',
    'Limpar ventilador do inversor': 'Clean inverter fan',
    'Substituir ventilador do inversor': 'Replace inverter fan',
    'Verificar tensão de alimentação': 'Check supply voltage',
    'Verificar alimentação trifásica': 'Check three-phase supply',
    'Instalar estabilizador de tensão': 'Install voltage stabilizer',
    'Instalar nobreak': 'Install UPS',
    'Verificar disjuntor': 'Check circuit breaker',
    'Verificar contator principal': 'Check main contactor',
    'Verificar relé térmico': 'Check thermal relay',
    'Substituir contator principal': 'Replace main contactor',
    'Substituir disjuntor': 'Replace circuit breaker',
    'Substituir fusível': 'Replace fuse',
    'Reapertar conexões': 'Tighten connections',
    'Limpar contatos': 'Clean contacts',
    'Ajustar torque dos bornes': 'Adjust terminal torque',
    'Verificar aperto dos cabos': 'Check cable tightness',
    'Substituir cabos danificados': 'Replace damaged cables',
    'Reparar cabos danificados': 'Repair damaged cables',
    'Reconectar cabos soltos': 'Reconnect loose cables',
    'Testar isolação com megôhmetro': 'Test insulation with megger',
    'Medir resistência de isolação': 'Measure insulation resistance',
    'Medir resistência ôhmica do motor': 'Measure motor winding resistance',
    'Testar continuidade dos cabos': 'Test cable continuity',
    'Verificar condição do motor': 'Check motor condition',
    'Substituir motor': 'Replace motor',
    'Rebobinar motor': 'Rewind motor',
    'Verificar escovas do motor': 'Check motor brushes',
    'Verificar rolamentos do motor': 'Check motor bearings',
    'Lubrificar rolamentos do motor': 'Lubricate motor bearings',
    'Verificar acoplamento': 'Check coupling',
    'Alinhar motor e carga': 'Align motor and load',
    'Verificar balanceamento': 'Check balancing',
    'Verificar ventoinha do motor': 'Check motor fan',
    'Instalar ventoinha auxiliar no motor': 'Install auxiliary motor fan',
    'Melhorar circulação de ar': 'Improve air circulation',
    'Instalar filtro de ar no painel': 'Install panel air filter',
    'Limpar filtro de ar': 'Clean air filter',
    'Substituir filtro de ar': 'Replace air filter',
    'Verificar obstrução de ar': 'Check air obstruction',
    'Reduzir ciclo de trabalho do motor': 'Reduce motor duty cycle',
    'Reduzir frequência de operação': 'Reduce operating frequency',
    'Reduzir corrente de saída': 'Reduce output current',
    'Ajustar limite de corrente': 'Adjust current limit',
    'Ajustar tempo de rampa': 'Adjust ramp time',
    'Ajustar parâmetros do motor': 'Adjust motor parameters',
    'Configurar dados de placa do motor': 'Configure motor nameplate data',
    'Realizar auto-ajuste do motor': 'Perform motor auto-tune',
    'Realizar identificação do motor': 'Perform motor identification',
    'Configurar tipo de controle': 'Configure control type',
    'Configurar referência de velocidade': 'Configure speed reference',
    'Configurar referência de torque': 'Configure torque reference',
    'Configurar limites de operação': 'Configure operating limits',
    'Configurar proteções do motor': 'Configure motor protections',
    'Configurar proteções do inversor': 'Configure inverter protections',
    'Restaurar padrão de fábrica': 'Restore factory defaults',
    'Atualizar firmware': 'Update firmware',
    'Substituir cartão de memória': 'Replace memory card',
    'Reinserir cartão de memória': 'Reinsert memory card',
    'Formatar cartão de memória': 'Format memory card',
    'Refazer parametrização': 'Reparameterize',
    'Verificar jumper de configuração': 'Check configuration jumper',
    'Verificar chave DIP': 'Check DIP switch',
    'Verificar jumper de terminação': 'Check termination jumper',
    'Configurar jumper de terminação': 'Configure termination jumper',
    'Substituir placa de controle': 'Replace control board',
    'Substituir placa de potência': 'Replace power board',
    'Substituir fonte auxiliar': 'Replace auxiliary power supply',
    'Substituir ventilador': 'Replace fan',
    'Limpar inversor': 'Clean inverter',
    'Limpar dissipador': 'Clean heatsink',
    'Verificar placa eletrônica': 'Check electronic board',
    'Secar placa eletrônica': 'Dry electronic board',
    'Limpar placa eletrônica': 'Clean electronic board',
    'Verificar conectores': 'Check connectors',
    'Reconectar conectores': 'Reconnect connectors',
    'Substituir conector danificado': 'Replace damaged connector',
    'Verificar cablagem': 'Check wiring',
    'Reparar cablagem': 'Repair wiring',
    'Substituir cablagem': 'Replace wiring',
    'Testar funcionamento': 'Test operation',
    'Realizar teste em vazio': 'Perform no-load test',
    'Realizar teste com carga': 'Perform load test',
    'Verificar sequência de fases': 'Check phase sequence',
    'Verificar tensão em todas as fases': 'Check voltage on all phases',
    'Substituir fusível de entrada': 'Replace input fuse',
    'Substituir fusível de potência': 'Replace power fuse',
    'Verificar fusível de entrada': 'Check input fuse',
    'Verificar fusível de potência': 'Check power fuse',
    'Inspecionar contator de entrada': 'Check input contactor',
    'Inspecionar contator de freio': 'Check brake contactor',
    'Substituir contator de entrada': 'Replace input contactor',
    'Verificar relé térmico do motor': 'Check motor thermal relay',
    'Ajustar relé térmico': 'Adjust thermal relay',
    'Substituir relé térmico': 'Replace thermal relay',
    'Verificar disjuntor do motor': 'Check motor circuit breaker',
    'Ajustar disjuntor do motor': 'Adjust motor circuit breaker',
    'Substituir disjuntor do motor': 'Replace motor circuit breaker',
    'Verificar transformador de entrada': 'Check input transformer',
    'Verificar reator de linha': 'Check line reactor',
    'Verificar filtro de linha': 'Check line filter',
    'Verificar contator de bypass': 'Check bypass contactor',
    'Acionar bypass manual': 'Activate manual bypass',
    'Colocar inversor em bypass': 'Put inverter in bypass',
    'Isolar inversor para manutenção': 'Isolate inverter for maintenance',
    'Religar inversor após manutenção': 'Restart inverter after maintenance',
    'Resetar inversor (desligar/ligar)': 'Reset inverter (power cycle)',
    'Aguardar resfriamento do inversor': 'Wait for inverter cooling',
    'Verificar temperatura ambiente': 'Check ambient temperature',
    'Reduzir temperatura ambiente': 'Reduce ambient temperature',
    'Instalar ar condicionado no painel': 'Install panel air conditioner',
    'Melhorar ventilação do painel': 'Improve panel ventilation',
    'Abrir persianas do painel': 'Open panel louvers',
    'Instalar exaustor no painel': 'Install panel exhaust fan',
    'Verificar dimensionamento do inversor': 'Check inverter sizing',
    'Redimensionar inversor': 'Resize inverter',
    'Verificar dimensionamento do motor': 'Check motor sizing',
    'Redimensionar motor': 'Resize motor',
    'Verificar aplicação': 'Check application',
    'Ajustar parâmetros de aplicação': 'Adjust application parameters',
    'Configurar velocidade máxima': 'Configure maximum speed',
    'Configurar velocidade mínima': 'Configure minimum speed',
    'Configurar torque máximo': 'Configure maximum torque',
    'Configurar corrente máxima': 'Configure maximum current',
    'Ajustar ganhos do controle PID': 'Adjust PID control gains',
    'Sintonizar controle PID': 'Tune PID control',
    'Ajustar compensação de escorregamento': 'Adjust slip compensation',
    'Configurar V/f': 'Configure V/f pattern',
    'Ajustar boost de torque': 'Adjust torque boost',
    'Configurar modo de controle': 'Configure control mode',
    'Configurar tipo de motor': 'Configure motor type',
    'Configurar tipo de encoder': 'Configure encoder type',
    'Configurar resolução do encoder': 'Configure encoder resolution',
    'Verificar polaridade do encoder': 'Check encoder polarity',
    'Verificar alinhamento do encoder': 'Check encoder alignment',
    'Verificar montagem do encoder': 'Check encoder mounting',
    'Verificar cabo de rede': 'Check network cable',
    'Verificar conector de rede': 'Check network connector',
    'Substituir cabo de rede': 'Replace network cable',
    'Verificar switch de rede': 'Check network switch',
    'Verificar endereço IP': 'Check IP address',
    'Configurar endereço IP': 'Configure IP address',
    'Configurar máscara de rede': 'Configure network mask',
    'Configurar gateway': 'Configure gateway',
    'Verificar nome de estação': 'Check station name',
    'Verificar ID de nó': 'Check node ID',
    'Configurar ID de nó': 'Configure node ID',
    'Verificar baudrate': 'Check baud rate',
    'Configurar baudrate': 'Configure baud rate',
    'Verificar paridade': 'Check parity',
    'Configurar paridade': 'Configure parity',
    'Verificar stop bits': 'Check stop bits',
    'Configurar stop bits': 'Configure stop bits',
    'Verificar protocolo de comunicação': 'Check communication protocol',
    'Configurar protocolo de comunicação': 'Configure communication protocol',
    'Verificar mapeamento de dados': 'Check data mapping',
    'Configurar mapeamento de dados': 'Configure data mapping',
    'Verificar tempo de ciclo': 'Check cycle time',
    'Configurar tempo de ciclo': 'Configure cycle time',
    'Verificar timeout de comunicação': 'Check communication timeout',
    'Ajustar timeout de comunicação': 'Adjust communication timeout',
    'Verificar resistência de terminação': 'Check termination resistance',
    'Instalar terminador de barramento': 'Install bus terminator',
    'Verificar terminador de barramento': 'Check bus terminator',
    'Substituir terminador de barramento': 'Replace bus terminator',
    'Verificar distância máxima do barramento': 'Check maximum bus distance',
    'Instalar repetidor de barramento': 'Install bus repeater',
    'Verificar fonte de alimentação da rede': 'Check network power supply',
    'Verificar estado da rede': 'Check network status',
    'Monitorar rede': 'Monitor network',
    'Verificar tráfego de rede': 'Check network traffic',
    'Verificar colisões na rede': 'Check network collisions',
    'Verificar erros de CRC': 'Check CRC errors',
    'Verificar integridade dos dados': 'Check data integrity',
    'Comparar checksum': 'Compare checksum',
};
