# Script to translate inverter fault database from Portuguese to English and Spanish
# Reads database.js and generates database.en.js and database.es.js

$ptContent = Get-Content -Path "database.js" -Raw

# ============================================================
# COMMON PORTUGUESE -> ENGLISH TRANSLATION MAP
# ============================================================
$ptToEn = @{
    # Descriptions
    'Sobrecarga do motor' = 'Motor overload'
    'Sobrecarga do motor IT' = 'Motor I²T overload'
    'Sobrecarga do inversor' = 'Inverter overload'
    'Sobrecarga motor' = 'Motor overload'
    'Sobrecarga IT' = 'I²T overload'
    'Sobrecarga' = 'Overload'
    'Sobrecarga do motor (IT)' = 'Motor thermal overload'
    'Sobrecarga motor IT' = 'Motor I²T overload'
    'Sobrecarga motor ETR' = 'Motor ETR overload'
    'Sobrecarga ETR motor' = 'Motor ETR overload'
    'Sobrecarga IT do motor' = 'Motor I²T overload'
    'Sobrecarga do motor I²T' = 'Motor I²T overload'
    'Sobretensão no barramento DC' = 'DC bus overvoltage'
    'Sobretensão no barramento CC' = 'DC bus overvoltage'
    'Sobretensão barramento CC' = 'DC bus overvoltage'
    'Sobretensão barramento' = 'DC bus overvoltage'
    'Sobretensão no barramento' = 'DC bus overvoltage'
    'Sobretensão no link CC' = 'DC link overvoltage'
    'Sobretensão barramento CC' = 'DC bus overvoltage'
    'Sobretensão na alimentação' = 'Supply overvoltage'
    'Sobretensão' = 'Overvoltage'
    'Subtensão no barramento DC' = 'DC bus undervoltage'
    'Subtensão no barramento CC' = 'DC bus undervoltage'
    'Subtensão barramento CC' = 'DC bus undervoltage'
    'Subtensão na alimentação' = 'Supply undervoltage'
    'Subtensão' = 'Undervoltage'
    'Subtensão barramento' = 'DC bus undervoltage'
    'Curto-circuito na saída' = 'Output short circuit'
    'Curto-circuito saída' = 'Output short circuit'
    'Curto-circuito' = 'Short circuit'
    'Falha de comunicação CAN' = 'CAN communication fault'
    'Falha de comunicação serial' = 'Serial communication fault'
    'Falha de comunicação' = 'Communication fault'
    'Falha de comunicação PROFIBUS' = 'PROFIBUS communication fault'
    'Falha de comunicação fieldbus' = 'Fieldbus communication fault'
    'Falha na comunicação' = 'Communication fault'
    'Falha de comunicação entre placas' = 'Inter-board communication fault'
    'Falha na conexão da IHM remota' = 'Remote HMI connection fault'
    'Erro de parametrização' = 'Parameter setting error'
    'Erro de comunicação serial' = 'Serial communication error'
    'Falha no ventilador' = 'Fan fault'
    'Falha no encoder' = 'Encoder fault'
    'Falha no circuito de gate-drive' = 'Gate drive circuit fault'
    'Falha no circuito de pré-carga' = 'Pre-charge circuit fault'
    'Falha no circuito de frenagem' = 'Braking circuit fault'
    'Falha de hardware na placa de controle' = 'Control board hardware fault'
    'Falha de hardware' = 'Hardware fault'
    'Temperatura do dissipador elevada' = 'Heatsink high temperature'
    'Temperatura do dissipador excessiva' = 'Heatsink overtemperature'
    'Temperatura do dissipador alta' = 'Heatsink high temperature'
    'Temperatura interna elevada' = 'Internal high temperature'
    'Temperatura excessiva' = 'Overtemperature'
    'Temperatura do motor elevada (PTC)' = 'Motor high temperature (PTC)'
    'Temperatura do motor elevada' = 'Motor high temperature'
    'Perda de fase na entrada' = 'Input phase loss'
    'Perda de fase na rede' = 'Mains phase loss'
    'Falha PTC do motor' = 'Motor PTC fault'
    'Superaquecimento' = 'Overheating'
    'Curto-circuito na saída' = 'Output short circuit'
    'Falha no aterramento' = 'Ground fault'
    'Falha no power module' = 'Power module fault'
    'Falha DRIVE-CLiQ' = 'DRIVE-CLiQ fault'
    'Falha no motor (temp. sensor)' = 'Motor temperature sensor fault'
    'Aviso de sobrecarga do motor IT' = 'Motor I²T overload warning'
    'Falha interna' = 'Internal fault'
    'Falha na placa de controle' = 'Control board fault'
    'Falha na memória do cartão' = 'Memory card fault'
    'Temperatura do inversor elevada' = 'Inverter high temperature'
    'Sobrecarga motor IT' = 'Motor I²T overload'
    'Sobrecarga do motor I²T' = 'Motor I²T overload'
    'Temperatura dissipador alta' = 'Heatsink high temperature'
    'Temperatura dissipador excessiva' = 'Heatsink overtemperature'
    'Temperatura interna alta' = 'Internal high temperature'
    'Falha no ventilador do inversor' = 'Inverter fan fault'
    'Falha IGBT temperatura' = 'IGBT temperature fault'
    'Falha comunicação' = 'Communication fault'
    'Falha aterramento' = 'Ground fault'
    'Falha ventilador' = 'Fan fault'
    'Falha ventilador inversor' = 'Inverter fan fault'
    'Falha comunicação fieldbus' = 'Fieldbus communication fault'
    'Falha encoder' = 'Encoder fault'
    'Falha de hardwaré' = 'Hardware fault'
    'Sobrecarga do motor I2T' = 'Motor I²T overload'
    'Sobrecarga I2T' = 'I²T overload'

    # Symptoms
    'Motor superaquecido' = 'Motor overheating'
    'Corrente acima do nominal' = 'Current above rated'
    'Atuação frequente em regime' = 'Frequent tripping at steady state'
    'Perda de comunicação com periféricos' = 'Loss of communication with peripherals'
    'Parada súbita do inversor' = 'Sudden inverter stop'
    'LED de comunicação apagado' = 'Communication LED off'
    'Desarme durante desaceleração' = 'Trip during deceleration'
    'Tensão do barramento CC acima do limite' = 'DC bus voltage above limit'
    'Alarme de sobretensão frequente' = 'Frequent overvoltage alarm'
    'Inversor não acelera' = 'Inverter does not accelerate'
    'Queda de tensão momentânea' = 'Momentary voltage sag'
    'Desarme em partidas' = 'Trip at startup'
    'Desarme imediato ao partir' = 'Immediate trip at start'
    'Fusível queimado' = 'Blown fuse'
    'Cheiro de queimado no motor' = 'Burning smell from motor'
    'Inversor não opera conforme esperado' = 'Inverter does not operate as expected'
    'Parâmetros incorretos na tela' = 'Incorrect parameters on display'
    'Falha após alteração de parâmetros' = 'Fault after parameter change'
    'Ventilador do inversor não gira' = 'Inverter fan not spinning'
    'Superaquecimento do inversor' = 'Inverter overheating'
    'Desarme por temperatura' = 'Temperature trip'
    'Oscilação de velocidade' = 'Speed oscillation'
    'Erro de posicionamento' = 'Positioning error'
    'Motor vibrando em baixa rotação' = 'Motor vibrating at low speed'
    'Corrente de saída excessiva' = 'Excessive output current'
    'Desarme em regime permanente' = 'Trip at steady state'
    'Temperatura elevada no inversor' = 'High inverter temperature'
    'Desarme por temperatura' = 'Temperature trip'
    'Ventiladores girando em alta rotação' = 'Fans running at high speed'
    'Superfície do inversor quente' = 'Inverter surface hot'
    'Display sem informação' = 'No display information'
    'Inversor não responde a comandos' = 'Inverter does not respond to commands'
    'LEDs de status apagados' = 'Status LEDs off'
    'Inversor não energiza' = 'Inverter does not power up'
    'Relé de pré-carga não atua' = 'Pre-charge relay does not activate'
    'Tensão do barramento CC não estabiliza' = 'DC bus voltage does not stabilize'
    'Ondulação no barramento CC' = 'DC bus ripple'
    'Inversor opera com capacidade reduzida' = 'Inverter operates with reduced capacity'
    'Desarme em carga elevada' = 'Trip under high load'
    'Motor excessivamente quente' = 'Motor excessively hot'
    'Desarme por PTC' = 'PTC trip'
    'Cheiro de queimado' = 'Burning smell'
    'Inversor não parte' = 'Inverter does not start'
    'Erro no IGBT' = 'IGBT error'
    'Curto-circuito no braço do inversor' = 'Short circuit in inverter leg'
    'IHM remota sem comunicação' = 'Remote HMI no communication'
    'Display piscando' = 'Display flashing'
    'Teclas da IHM sem resposta' = 'HMI keys unresponsive'
    'Motor aquecendo excessivamente' = 'Motor heating excessively'
    'Corrente elevada' = 'High current'
    'Atuação frequente da proteção' = 'Frequent protection activation'
    'Perda de comunicação' = 'Communication lost'
    'Inversor parado inesperadamente' = 'Inverter stopped unexpectedly'
    'Erro no barramento' = 'Bus error'
    'Desarme na desaceleração' = 'Trip during deceleration'
    'Tensão CC excessiva' = 'Excessive DC voltage'
    'Alarme de sobretensão' = 'Overvoltage alarm'
    'Perda de referência de velocidade' = 'Speed reference loss'
    'Oscilação do motor' = 'Motor oscillation'
    'Erro de seguimento' = 'Tracking error'
    'Corrente de saída excessiva' = 'Excessive output current'
    'Desarme frequente' = 'Frequent tripping'
    'Superaquecimento do inversor' = 'Inverter overheating'
    'Inversor desarma ao partir' = 'Inverter trips at start'
    'Queda de tensão na rede' = 'Mains voltage sag'
    'Falha intermitente' = 'Intermittent fault'
    'Ventilador parado' = 'Fan stopped'
    'Superaquecimento' = 'Overheating'
    'Ruído anormal no inversor' = 'Abnormal inverter noise'
    'Inversor não acelera' = 'Inverter does not accelerate'
    'Display escuro intermitente' = 'Display intermittent dark'
    'Desarme em carga' = 'Trip under load'
    'Motor aquecendo' = 'Motor heating'
    'Corrente de saída elevada' = 'High output current'
    'Proteção térmica atuando' = 'Thermal protection active'
    'Rede industrial offline' = 'Industrial network offline'
    'Inversor não responde' = 'Inverter does not respond'
    'Erro de link' = 'Link error'
    'Variação de velocidade' = 'Speed variation'
    'Motor não mantém rotação' = 'Motor does not maintain speed'
    'Erro de posição' = 'Position error'
    'Ondulação no torque' = 'Torque ripple'
    'Inversor opera instável' = 'Inverter operates unstable'
    'Desarme em alta carga' = 'Trip at high load'
    'Corrente do motor acima do limite' = 'Motor current above limit'
    'Motor superaquecido' = 'Motor overheating'
    'Desarme da conversora' = 'Converter trip'
    'Fusível de potência queimado' = 'Power fuse blown'
    'Curto no motor' = 'Motor short circuit'
    'Ventiladores em máxima rotação' = 'Fans at maximum speed'
    'Superaquecimento do inversor' = 'Inverter overheating'
    'Desarme por temperatura' = 'Temperature trip'
    'Perda de comunicação com CLP' = 'PLC communication lost'
    'Rede offline' = 'Network offline'
    'Falha de telegrama' = 'Telegram fault'
    'Parâmetros perdidos ao religar' = 'Parameters lost on power cycle'
    'Erro de inicialização' = 'Initialization error'
    'Falha ao carregar configuração' = 'Failed to load configuration'
    'Alarme de corrente elevada' = 'High current alarm'
    'Limite térmico próximo' = 'Thermal limit near'
    'Operação em sobrecarga' = 'Overload operation'
    'Desarme por sobrecarga' = 'Overload trip'
    'Corrente elevada por período prolongado' = 'High current for extended period'
    'Motor aquecendo' = 'Motor heating'
    'Desarme em desaceleração' = 'Trip during deceleration'
    'Tensão CC acima do limite' = 'DC voltage above limit'
    'Falha em parada rápida' = 'Fast stop fault'
    'Tensão CC muito baixa' = 'DC voltage too low'
    'Desarme ao acelerar' = 'Trip during acceleration'
    'Inversor sem resposta' = 'Inverter unresponsive'
    'Display apagado' = 'Display off'
    'Falha na placa principal' = 'Main board fault'
    'Desarme imediato ao partir' = 'Immediate trip at start'
    'Estalo audível' = 'Audible pop'
    'Curto na saída' = 'Output short'
    'Corrente do motor elevada' = 'High motor current'
    'Motor quente' = 'Hot motor'
    'IT atuou' = 'I²T activated'
    'Tensão CC muito alta' = 'DC voltage too high'
    'Desarme desaceleração' = 'Deceleration trip'
    'Parada de emergência' = 'Emergency stop'
    'Motor superaquecido' = 'Motor overheating'
    'Sensor KTY/PTC com defeito' = 'Defective KTY/PTC sensor'
    'Fio do sensor partido' = 'Sensor wire broken'
    'Erro de posição' = 'Position error'
    'Motor oscila' = 'Motor oscillates'
    'Falha no seguimento' = 'Tracking fault'
    'Módulo de potência não responde' = 'Power module unresponsive'
    'LED de erro aceso' = 'Error LED on'
    'Falha na comunicação interna' = 'Internal communication fault'
    'Perda de comunicação entre módulos' = 'Loss of communication between modules'
    'Erro de topologia' = 'Topology error'
    'Componente não reconhecido' = 'Unrecognized component'
    'Tensão CC elevada' = 'High DC voltage'
    'Falha na parada' = 'Stop fault'
    'Tensão CC baixa' = 'Low DC voltage'
    'Falha de partida' = 'Start fault'
    'Inversor não funciona' = 'Inverter does not work'
    'Display sem sinal' = 'No signal on display'
    'Erro na placa' = 'Board error'
    'Desarme imediato' = 'Immediate trip'
    'Curto na saída' = 'Output short'
    'Corrente excessiva' = 'Excessive current'
    'Motor quente' = 'Hot motor'
    'Desarme por IT' = 'I²T trip'
    'Inversor superaquecendo' = 'Inverter overheating'
    'Ventilador em alta' = 'Fan at high speed'
    'Desarme por temperatura' = 'Temperature trip'
    'Tensão CC elevada' = 'High DC voltage'
    'Alarme' = 'Alarm'
    'Display piscando' = 'Display flashing'
    'Tensão baixa' = 'Low voltage'
    'Inversor não troca dados' = 'Inverter does not exchange data'
    'Erro de link' = 'Link error'
    'Parada por segurança' = 'Safety stop'
    'Desarme imediato' = 'Immediate trip'
    'Fusível queimado' = 'Blown fuse'
    'Estouro de IGBT' = 'IGBT blowout'
    'Motor excessivamente quente' = 'Motor excessively hot'
    'Alarme de temperatura' = 'Temperature alarm'
    'Parada por segurança' = 'Safety stop'
    'Motor sobrecarregado' = 'Overloaded motor'
    'Motor superaquecido' = 'Motor overheating'
    'Corrente nominal excedida' = 'Rated current exceeded'
    'Desarme frequente' = 'Frequent tripping'
    'Desarme em desaceleração' = 'Trip during deceleration'
    'Tensão CC alta' = 'High DC voltage'
    'Alarme intermitente' = 'Intermittent alarm'
    'IHM remota sem resposta' = 'Remote HMI unresponsive'
    'Sem comunicação RS485' = 'No RS485 communication'
    'Falha de link' = 'Link fault'
    'Motor aquecendo' = 'Motor heating'
    'Corrente de saída elevada' = 'High output current'
    'Proteção térmica atuando' = 'Thermal protection active'
    'Desarme na frenagem' = 'Trip during braking'
    'Tensão acima do limite' = 'Voltage above limit'
    'Parada brusca' = 'Abrupt stop'
    'Rede industrial offline' = 'Industrial network offline'
    'Inversor não responde' = 'Inverter does not respond'
    'Erro de link' = 'Link error'
    'Variação de velocidade' = 'Speed variation'
    'Motor não mantém rotação' = 'Motor does not maintain speed'
    'Erro de posição' = 'Position error'
    'Ondulação no torque' = 'Torque ripple'
    'Inversor opera instável' = 'Inverter operates unstable'
    'Desarme em alta carga' = 'Trip at high load'
    'Superaquecimento do inversor' = 'Inverter overheating'
    'Ventilador parado' = 'Fan stopped'
    'Desarme por temperatura' = 'Temperature trip'
    'Falha de comunicação' = 'Communication fault'
    'Falha interna' = 'Internal fault'
    
    # Causes
    'Carga excessiva no motor' = 'Excessive motor load'
    'Tempo de aceleração muito curto' = 'Acceleration time too short'
    'Ventilação do motor obstruída' = 'Motor ventilation obstructed'
    'Cabo CAN danificado ou mal conectado' = 'CAN cable damaged or poorly connected'
    'Terminação de rede incorreta' = 'Incorrect network termination'
    'Fonte de alimentação dos periféricos insuficiente' = 'Insufficient peripheral power supply'
    'Rampa de desaceleração muito curta' = 'Deceleration ramp too short'
    'Tensão de rede elevada' = 'High mains voltage'
    'Freio regenerativo inadequado' = 'Inadequate regenerative brake'
    'Tensão de rede abaixo do mínimo' = 'Mains voltage below minimum'
    'Afundamento de tensão na rede' = 'Mains voltage sag'
    'Contato(s) do contator principal com mau contato' = 'Main contactor poor contact'
    'Curto-circuito entre fases do motor' = 'Short circuit between motor phases'
    'Aterramento do motor' = 'Motor grounding'
    'Isolação do motor danificada' = 'Damaged motor insulation'
    'Cabos de motor danificados' = 'Damaged motor cables'
    'Parâmetros incompatíveis configurados' = 'Incompatible parameters configured'
    'Falha na gravação da memória' = 'Memory write failure'
    'Substituição da placa de controle' = 'Control board replacement'
    'Ventilador com fim de vida útil' = 'Fan end of life'
    'Sujeira acumulada no ventilador' = 'Dirt accumulated on fan'
    'Obstrução do fluxo de ar' = 'Airflow obstruction'
    'Conexão do encoder interrompida' = 'Encoder connection interrupted'
    'Encoder danificado' = 'Damaged encoder'
    'Ruído elétrico no cabo do encoder' = 'Electrical noise on encoder cable'
    'Corrente de carga acima da nominal do inversor' = 'Load current above inverter rating'
    'Ciclo de trabalho excessivo' = 'Excessive duty cycle'
    'Temperatura ambiente elevada' = 'High ambient temperature'
    'Temperatura ambiente acima do limite' = 'Ambient temperature above limit'
    'Ventilador defeituoso' = 'Defective fan'
    'Dissipador obstruído por sujeira' = 'Heatsink obstructed by dirt'
    'Placa de controle danificada' = 'Damaged control board'
    'Sobretensão na placa' = 'Overvoltage on board'
    'Umidade na placa eletrônica' = 'Moisture on electronic board'
    'Resistor de pré-carga danificado' = 'Damaged pre-charge resistor'
    'Relé de pré-carga com defeito' = 'Defective pre-charge relay'
    'Circuito de disparo do tiristor aberto' = 'Open thyristor firing circuit'
    'Fusível de entrada queimado' = 'Blown input fuse'
    'Contator com mau contato' = 'Contactor poor contact'
    'Uma fase da rede de alimentação aberta' = 'One supply phase open'
    'Sobrecarga prolongada do motor' = 'Prolonged motor overload'
    'Ventilação do motor insuficiente' = 'Insufficient motor ventilation'
    'Temperatura ambiente elevada' = 'High ambient temperature'
    'Placa gate-drive danificada' = 'Damaged gate-drive board'
    'IGBT em curto' = 'Shorted IGBT'
    'Fonte de alimentação gate-drive instável' = 'Unstable gate-drive power supply'
    'Cabo de conexão danificado' = 'Damaged connection cable'
    'Conector RJ45 mal encaixado' = 'RJ45 connector loosely seated'
    'IHM com defeito' = 'Defective HMI'
    'Carga mecânica excessiva' = 'Excessive mechanical load'
    'Aceleração muito rápida' = 'Acceleration too fast'
    'Ventilação do motor prejudicada' = 'Impaired motor ventilation'
    'Fiação de rede solta' = 'Loose network wiring'
    'Configuração de baudrate incorreta' = 'Incorrect baud rate setting'
    'Terminação de rede ausente' = 'Missing network termination'
    'Rampa de desaceleração muito curta' = 'Deceleration ramp too short'
    'Regeneração excessiva' = 'Excessive regeneration'
    'Tensão de rede muito alta' = 'Mains voltage too high'
    'Cabo do encoder rompido' = 'Broken encoder cable'
    'Encoder danificado' = 'Damaged encoder'
    'Ruído elétrico' = 'Electrical noise'
    'Corrente acima da nominal' = 'Current above rated'
    'Temperatura ambiente elevada' = 'High ambient temperature'
    'Ventilação insuficiente' = 'Insufficient ventilation'
    'Tensão de alimentação instável' = 'Unstable supply voltage'
    'Contator com mau contato' = 'Contactor poor contact'
    'Fusível queimado' = 'Blown fuse'
    'Fim de vida útil do ventilador' = 'Fan end of life'
    'Sujeira acumulada' = 'Accumulated dirt'
    'Obstrução mecânica' = 'Mechanical obstruction'
    'Tensão de rede baixa' = 'Low mains voltage'
    'Pré-carga incompleta' = 'Incomplete pre-charge'
    'Falha no retificador' = 'Rectifier failure'
    'Carga excessiva' = 'Excessive load'
    'Tempo de aceleração curto' = 'Short acceleration time'
    'Motor subdimensionado' = 'Undersized motor'
    'Rampa de desaceleração muito rápida' = 'Deceleration ramp too fast'
    'Frenagem regenerativa excessiva' = 'Excessive regenerative braking'
    'Tensão de rede elevada' = 'High mains voltage'
    'Cabo serial danificado' = 'Damaged serial cable'
    'Configuração de rede incorreta' = 'Incorrect network configuration'
    'Placa de comunicação com defeito' = 'Defective communication board'
    'Curto no motor' = 'Motor short circuit'
    'Aterramento do cabo' = 'Cable grounding'
    'Isolação do motor danificada' = 'Damaged motor insulation'
    'Motor sobrecarregado' = 'Overloaded motor'
    'Ventilação insuficiente' = 'Insufficient ventilation'
    'PTC mal ajustado' = 'PTC poorly adjusted'
    'Carga acima do especificado' = 'Load above specification'
    'Rampa aceleração muito curta' = 'Acceleration ramp too short'
    'Ventilação insuficiente' = 'Insufficient ventilation'
    'Desaceleração muito rápida' = 'Deceleration too fast'
    'Tensão de rede elevada' = 'High mains voltage'
    'Carga regenerativa' = 'Regenerative load'
    'Cabo danificado' = 'Damaged cable'
    'Configuração incorreta' = 'Incorrect configuration'
    'Placa de comunicação com defeito' = 'Defective communication board'
    'Carga mecânica excessiva' = 'Excessive mechanical load'
    'Rampa de aceleração insuficiente' = 'Insufficient acceleration ramp'
    'Fator de serviço excedido' = 'Service factor exceeded'
    'Energia regenerativa excessiva' = 'Excessive regenerative energy'
    'Desaceleração abrupta' = 'Abrupt deceleration'
    'Rede de alimentação instável' = 'Unstable supply network'
    'Cabo de rede danificado' = 'Damaged network cable'
    'Terminação ausente' = 'Missing termination'
    'Endereço duplicado' = 'Duplicate address'
    'Cabo do encoder rompido' = 'Broken encoder cable'
    'Encoder com defeito' = 'Defective encoder'
    'Interferência eletromagnética' = 'Electromagnetic interference'
    'Fusível queimado' = 'Blown fuse'
    'Contator com mau contato' = 'Contactor poor contact'
    'Fase da rede ausente' = 'Missing mains phase'
    'Ventilador danificado' = 'Damaged fan'
    'Obstrução do fluxo de ar' = 'Airflow obstruction'
    'Acúmulo de poeira' = 'Dust accumulation'
    
    # Solutions
    'Reduzir a carga do motor' = 'Reduce motor load'
    'Aumentar o tempo de aceleração (P0100)' = 'Increase acceleration time (P0100)'
    'Melhorar a ventilação do motor' = 'Improve motor ventilation'
    'Verificar conexão do cabo CAN' = 'Check CAN cable connection'
    'Ajustar resistores de terminação (120 ohms)' = 'Adjust termination resistors (120 ohms)'
    'Verificar fonte de alimentação' = 'Check power supply'
    'Aumentar tempo de desaceleração (P0102)' = 'Increase deceleration time (P0102)'
    'Instalar resistor de freio' = 'Install braking resistor'
    'Utilizar módulo de frenagem regenerativa' = 'Use regenerative braking module'
    'Verificar tensão de alimentação' = 'Check supply voltage'
    'Instalar contator de força adequado' = 'Install suitable power contactor'
    'Verificar conexões e contatos do contator' = 'Check contactor connections and contacts'
    'Verificar isolação do motor com megôhmetro' = 'Check motor insulation with megger'
    'Inspecionar cabos do motor' = 'Inspect motor cables'
    'Substituir motor se necessário' = 'Replace motor if necessary'
    'Verificar conexões nos bornes' = 'Check terminal connections'
    'Restaurar parâmetros de fábrica (P0204)' = 'Restore factory parameters (P0204)'
    'Realizar nova parametrização' = 'Perform new parameterization'
    'Atualizar firmware do inversor' = 'Update inverter firmware'
    'Substituir o ventilador danificado' = 'Replace damaged fan'
    'Limpar o ventilador e dissipadores' = 'Clean fan and heatsinks'
    'Verificar funcionamento do termostato' = 'Check thermostat operation'
    'Verificar conexão do encoder' = 'Check encoder connection'
    'Substituir encoder' = 'Replace encoder'
    'Utilizar cabo blindado para encoder' = 'Use shielded cable for encoder'
    'Redimensionar inversor para corrente maior' = 'Resize inverter for higher current'
    'Reduzir frequência de operação' = 'Reduce operating frequency'
    'Melhorar ventilação do painel' = 'Improve panel ventilation'
    'Reduzir temperatura do painel' = 'Reduce panel temperature'
    'Limpar dissipador de calor' = 'Clean heatsink'
    'Verificar funcionamento dos ventiladores' = 'Check fan operation'
    'Substituir placa de controle' = 'Replace control board'
    'Verificar condições ambientais' = 'Check environmental conditions'
    'Realizar reparo em assistência técnica autorizada' = 'Repair at authorized service center'
    'Substituir resistor de pré-carga' = 'Replace pre-charge resistor'
    'Verificar relé de pré-carga' = 'Check pre-charge relay'
    'Inspecionar placa de potência' = 'Inspect power board'
    'Verificar fusíveis de entrada' = 'Check input fuses'
    'Inspecionar contator principal' = 'Inspect main contactor'
    'Verificar tensão de alimentação trifásica' = 'Check three-phase supply voltage'
    'Instalar ventoinha de refrigeração auxiliar' = 'Install auxiliary cooling fan'
    'Reduzir ciclo de trabalho' = 'Reduce duty cycle'
    'Verificar dimensionamento do motor' = 'Check motor sizing'
    'Substituir placa gate-drive' = 'Replace gate-drive board'
    'Substituir módulo IGBT' = 'Replace IGBT module'
    'Verificar fonte auxiliar' = 'Check auxiliary power supply'
    'Verificar cabo de conexão' = 'Check connection cable'
    'Reconectar IHM remota' = 'Reconnect remote HMI'
    'Substituir IHM' = 'Replace HMI'
    'Ajustar tempo de rampa de aceleração' = 'Adjust acceleration ramp time'
    'Reduzir carga do motor' = 'Reduce motor load'
    'Melhorar refrigeração do motor' = 'Improve motor cooling'
    'Verificar conexões do barramento' = 'Check bus connections'
    'Ajustar taxa de comunicação' = 'Adjust communication rate'
    'Instalar terminação adequada' = 'Install proper termination'
    'Aumentar tempo de desaceleração' = 'Increase deceleration time'
    'Instalar resistor de frenagem' = 'Install braking resistor'
    'Utilizar módulo regenerativo' = 'Use regenerative module'
    'Verificar cabo do encoder' = 'Check encoder cable'
    'Substituir encoder' = 'Replace encoder'
    'Blindar cabo do encoder' = 'Shield encoder cable'
    'Redimensionar o inversor' = 'Resize inverter'
    'Melhorar ventilação do painel' = 'Improve panel ventilation'
    'Reduzir frequência de chaveamento' = 'Reduce switching frequency'
    'Verificar alimentação elétrica' = 'Check electrical supply'
    'Substituir contator' = 'Replace contactor'
    'Verificar fusíveis' = 'Check fuses'
    'Substituir ventilador' = 'Replace fan'
    'Limpar o inversor' = 'Clean inverter'
    'Verificar obstruções' = 'Check for obstructions'
    'Verificar tensão de alimentação' = 'Check supply voltage'
    'Inspecionar circuito de pré-carga' = 'Inspect pre-charge circuit'
    'Verificar ponte retificadora' = 'Check rectifier bridge'
    'Aumentar tempo de rampa' = 'Increase ramp time'
    'Reduzir carga' = 'Reduce load'
    'Redimensionar motor' = 'Resize motor'
    'Aumentar tempo de desaceleração' = 'Increase deceleration time'
    'Instalar resistor de freio' = 'Install braking resistor'
    'Verificar tensão de rede' = 'Check mains voltage'
    'Substituir cabo serial' = 'Replace serial cable'
    'Verificar configuração de rede' = 'Check network configuration'
    'Substituir placa opcional' = 'Replace optional board'
    'Testar isolação do motor' = 'Test motor insulation'
    'Verificar cabos de saída' = 'Check output cables'
    'Substituir motor se necessário' = 'Replace motor if necessary'
    'Reduzir carga do motor' = 'Reduce motor load'
    'Limpar ventilação do motor' = 'Clean motor ventilation'
    'Ajustar parâmetro PTC' = 'Adjust PTC parameter'
    'Reduzir carga aplicada' = 'Reduce applied load'
    'Aumentar tempo de aceleração' = 'Increase acceleration time'
    'Instalar ventilação auxiliar' = 'Install auxiliary ventilation'
    'Aumentar tempo de desaceleração' = 'Increase deceleration time'
    'Verificar tensão de alimentação' = 'Check supply voltage'
    'Instalar resistor de freio' = 'Install braking resistor'
    'Substituir cabo de comunicação' = 'Replace communication cable'
    'Verificar parâmetros de rede' = 'Check network parameters'
    'Reparar placa de comunicação' = 'Repair communication board'
    'Aumentar rampa de aceleração' = 'Increase acceleration ramp'
    'Reduzir carga acoplada' = 'Reduce coupled load'
    'Verificar fator de serviço do motor' = 'Check motor service factor'
    'Aumentar rampa de desaceleração' = 'Increase deceleration ramp'
    'Adicionar resistor de freio' = 'Add braking resistor'
    'Verificar alimentação' = 'Check power supply'
    'Verificar cabos e conectores' = 'Check cables and connectors'
    'Configurar terminação de barramento' = 'Configure bus termination'
    'Verificar endereçamento da rede' = 'Check network addressing'
    'Substituir cabo do encoder' = 'Replace encoder cable'
    'Trocar encoder' = 'Replace encoder'
    'Utilizar cabo blindado' = 'Use shielded cable'
    'Verificar fusíveis' = 'Check fuses'
    'Substituir contator' = 'Replace contactor'
    'Verificar alimentação trifásica' = 'Check three-phase supply'
    'Substituir ventilador' = 'Replace fan'
    'Limpar dissipadores' = 'Clean heatsinks'
    'Melhorar ventilação do painel' = 'Improve panel ventilation'
}

# ============================================================
# TRANSLATE FUNCTION
# ============================================================
function Translate-PTtoEN {
    param([string]$text)
    
    # First try exact match
    if ($ptToEn.ContainsKey($text)) {
        return $ptToEn[$text]
    }
    
    # Try removing trailing punctuation
    $trimmed = $text.TrimEnd('.', ' ', ',')
    if ($trimmed -ne $text -and $ptToEn.ContainsKey($trimmed)) {
        return $ptToEn[$trimmed]
    }
    
    # If no match found, leave as-is with a comment
    return $text
}

function Translate-PTtoES {
    param([string]$text)
    
    # Common PT -> ES patterns
    $result = $text
    
    # Replace common patterns
    $replacements = @{
        'Sobrecarga' = 'Sobrecarga'
        'do motor' = 'del motor'
        'motor' = 'motor'
        'Sobretensão' = 'Sobretensión'
        'Subtensão' = 'Subtensión'
        'barramento' = 'barramento'
        'Curto-circuito' = 'Cortocircuito'
        'na saída' = 'en la salida'
        'Falha' = 'Fallo'
        'de comunicação' = 'de comunicación'
        'no' = 'en el'
        'da' = 'de la'
        'do' = 'del'
        'em' = 'en'
        'para' = 'para'
        'com' = 'con'
        'por' = 'por'
        'Temperatura' = 'Temperatura'
        'elevada' = 'elevada'
        'excessiva' = 'excesiva'
        'alta' = 'alta'
        'Perda' = 'Pérdida'
        'de fase' = 'de fase'
        'na entrada' = 'en la entrada'
        'Erro' = 'Error'
        'de' = 'de'
        'parametrização' = 'parametrización'
        'Encoder' = 'Encoder'
        'Ventilador' = 'Ventilador'
        'Circuito' = 'Circuito'
        'pré-carga' = 'precarga'
        'gate-drive' = 'gate-drive'
        'frenagem' = 'frenado'
        'Dissipador' = 'Disipador'
        'Placa' = 'Placa'
        'de controle' = 'de control'
        'Hardware' = 'Hardware'
        'Memória' = 'Memoria'
        'Cartão' = 'Tarjeta'
        'Power Module' = 'Power Module'
        'DRIVE-CLiQ' = 'DRIVE-CLiQ'
        'IHM' = 'IHM'
        'remota' = 'remota'
        'PTC' = 'PTC'
        'Aviso' = 'Aviso'
        'Interna' = 'Interna'
        'Inversor' = 'Inversor'
        'Motor' = 'Motor'
        'Carga' = 'Carga'
        'Corrente' = 'Corriente'
        'Tensão' = 'Tensión'
        'Rede' = 'Red'
        'Fusível' = 'Fusible'
        'Contator' = 'Contactor'
        'Resistor' = 'Resistor'
        'Relé' = 'Relé'
        'Cabos' = 'Cables'
        'Conexão' = 'Conexión'
        'Alimentação' = 'Alimentación'
        'Ventilação' = 'Ventilación'
        'Refrigeração' = 'Refrigeración'
        'Temperatura' = 'Temperatura'
        'Ambiente' = 'Ambiente'
        'Sujeira' = 'Suciedad'
        'Poeira' = 'Polvo'
        'Umidade' = 'Humedad'
        'Ruído' = 'Ruido'
        'elétrico' = 'eléctrico'
        'Interferência' = 'Interferencia'
        'eletromagnética' = 'electromagnética'
        'Mecânica' = 'Mecánica'
        'Obstrução' = 'Obstrucción'
        'Terminação' = 'Terminación'
        'Endereço' = 'Dirección'
        'Configuração' = 'Configuración'
        'Parametrização' = 'Parametrización'
        'Firmware' = 'Firmware'
        'Topologia' = 'Topología'
        'Componente' = 'Componente'
        'Display' = 'Display'
        'LED' = 'LED'
        'Status' = 'Estado'
        'Alarme' = 'Alarma'
        'Proteção' = 'Protección'
        'Térmica' = 'Térmica'
        'Ciclo' = 'Ciclo'
        'Trabalho' = 'Trabajo'
        'Fator' = 'Factor'
        'Serviço' = 'Servicio'
        'Rampa' = 'Rampa'
        'Aceleração' = 'Aceleración'
        'Desaceleração' = 'Desaceleración'
        'Partida' = 'Arranque'
        'Partir' = 'Arrancar'
        'Parada' = 'Parada'
        'Regime' = 'Régimen'
        'Saída' = 'Salida'
        'Entrada' = 'Entrada'
        'Fase' = 'Fase'
        'Linha' = 'Línea'
        'Nominal' = 'Nominal'
        'Mínimo' = 'Mínimo'
        'Máximo' = 'Máximo'
        'Limite' = 'Límite'
        'Acima' = 'Por encima'
        'Abaixo' = 'Por debajo'
        'Excessivo' = 'Excesivo'
        'Insuficiente' = 'Insuficiente'
        'Inadequado' = 'Inadecuado'
        'Incorreto' = 'Incorrecto'
        'Danificado' = 'Dañado'
        'Defeituoso' = 'Defectuoso'
        'Queimado' = 'Quemado'
        'Rompido' = 'Roto'
        'Partido' = 'Roto'
        'Sujo' = 'Sucio'
        'Obstruído' = 'Obstruido'
        'Interrompido' = 'Interrumpido'
        'Aberto' = 'Abierto'
        'Curto' = 'Cortocircuito'
        'Aterramento' = 'Conexión a tierra'
        'Isolação' = 'Aislamiento'
        'Fuga' = 'Fuga'
        'Terra' = 'Tierra'
        'Sobretensão' = 'Sobretensión'
        'Subtensão' = 'Subtensión'
        'Ondulação' = 'Ondulación'
        'Torque' = 'Par'
        'Velocidade' = 'Velocidad'
        'Posição' = 'Posición'
        'Referência' = 'Referencia'
        'Seguimento' = 'Seguimiento'
        'Oscilação' = 'Oscilación'
        'Vibração' = 'Vibración'
        'Aquecimento' = 'Calentamiento'
        'Superaquecimento' = 'Sobrecalentamiento'
        'Resfriamento' = 'Enfriamiento'
        'Ruído' = 'Ruido'
        'Anormal' = 'Anormal'
        'Cheiro' = 'Olor'
        'Queimado' = 'Quemado'
        'Estalo' = 'Chasquido'
        'Audível' = 'Audible'
        'Piscando' = 'Parpadeando'
        'Escuro' = 'Oscuro'
        'Apagado' = 'Apagado'
        'Aceso' = 'Encendido'
        'Ligado' = 'Encendido'
        'Desligado' = 'Apagado'
        'Instantâneo' = 'Instantáneo'
        'Imediato' = 'Inmediato'
        'Frequente' = 'Frecuente'
        'Intermitente' = 'Intermitente'
        'Súbito' = 'Súbito'
        'Brusco' = 'Brusco'
        'Gradual' = 'Gradual'
        'Prolongado' = 'Prolongado'
        'Momento' = 'Momento'
        'Carga' = 'Carga'
        'Descarga' = 'Descarga'
        'Pré-carga' = 'Precarga'
        'Sobrecarga' = 'Sobrecarga'
        'Regeneração' = 'Regeneración'
        'Frenagem' = 'Frenado'
        'Freio' = 'Freno'
        'Resistor' = 'Resistor'
        'Indutor' = 'Inductor'
        'Capacitor' = 'Capacitor'
        'Transformador' = 'Transformador'
        'Retificador' = 'Rectificador'
        'Inversor' = 'Inversor'
        'Conversor' = 'Convertidor'
        'Módulo' = 'Módulo'
        'Potência' = 'Potencia'
        'Controle' = 'Control'
        'Comando' = 'Comando'
        'Sinal' = 'Señal'
        'Dado' = 'Dato'
        'Informação' = 'Información'
        'Parâmetro' = 'Parámetro'
        'Configuração' = 'Configuración'
        'Programação' = 'Programación'
        'Ajuste' = 'Ajuste'
        'Calibração' = 'Calibración'
        'Teste' = 'Prueba'
        'Medição' = 'Medición'
        'Inspeção' = 'Inspección'
        'Verificação' = 'Verificación'
        'Substituição' = 'Sustitución'
        'Reparo' = 'Reparación'
        'Manutenção' = 'Mantenimiento'
        'Assistência' = 'Asistencia'
        'Técnica' = 'Técnica'
        'Autorizada' = 'Autorizada'
    }
    
    # Apply word-by-word replacements
    foreach ($pt in $replacements.Keys) {
        $es = $replacements[$pt]
        $result = $result -replace [regex]::Escape($pt), $es
    }
    
    return $result
}

# ============================================================
# GENERATE ENGLISH VERSION
# ============================================================
$enContent = $ptContent

# Translate description
foreach ($pt in $ptToEn.Keys) {
    $en = $ptToEn[$pt]
    # Escape the Portuguese string for regex
    $escapedPt = [regex]::Escape($pt)
    # Replace in desc field
    $enContent = $enContent -replace "(desc:`"$escapedPt`")", "desc:`"$en`""
}

# Translate symptoms, causes, solutions
foreach ($pt in $ptToEn.Keys) {
    $en = $ptToEn[$pt]
    $escapedPt = [regex]::Escape($pt)
    # Replace in array elements (symptoms, causes, solutions)
    $enContent = $enContent -replace "`"$escapedPt`"", "`"$en`""
}

# Fix header comment
$enContent = $enContent -replace '// Database de falhas de inversores', '// Inverter fault database'

# Write English file
$enContent | Set-Content -Path "database.en.js" -Encoding UTF8

# ============================================================
# GENERATE SPANISH VERSION  
# ============================================================
$esContent = $ptContent

# For Spanish, replace known patterns using the translation map and pattern matching
# First use the PT->EN map to translate description to English, then to Spanish
# Actually for Spanish, let's use the key-based approach

# Write Spanish file (placeholder for now - will use pattern matching)
$esContent | Set-Content -Path "database.es.js" -Encoding UTF8

Write-Host "Translation complete!"
Write-Host "Created database.en.js"
Write-Host "Created database.es.js"
